version: "3.6"

services:
  base-static: &base-static
    build:
      dockerfile: config/docker/Dockerfile.assets
      context: .
    image: static:v1
    networks:
      - main
    environment:
      - STATIC_PATH=/app/static
    volumes:
      - ./roulette/src:/app/src

  base-app: &base-app
    build:
      dockerfile: config/docker/Dockerfile.app
      context: .
    image: app:v1
    networks:
      - main
    volumes:
      - ./:/app

  webpack:
    <<: *base-static
    stdin_open: true
    command: npm start

  admin:
    <<: *base-app
    command: [
        "python3.8",
        "-m",
        "SteamRoulette.admin",
        "--port",
        "5000",
        "--host",
        "0.0.0.0",
        "--config",
        "/app/config/app.yaml",
        "--debug",
        "true",
    ]
  alembic:
    <<: *base-app
    volumes:
      - "./SteamRoulette/:/app/SteamRoulette"
      - "./config/:/app/config"
      - "./alembic.ini:/app/alembic.ini"
      - type: bind
        source: "./db_schema/alembic"
        target: "/app/db_schema/alembic"
    entrypoint: alembic -n alembic:docker

  postgres:
    image: postgres:11.9-alpine
    ports:
      - "5433:5432"
    networks:
      main:
        aliases:
          - postgres
    env_file:
      - ./config/docker/envs/postgres.env
    volumes:
      - "./.volumes/pg/:/var/lib/postgresql/data/"

  nginx:
    image: nginx:1.14.0-alpine
    ports:
      - "5000:5000"
    volumes:
      - "./config/docker/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      main:
        aliases:
          - nginx
    depends_on:
      - admin
      - webpack

networks:
  main:
    driver: bridge
