version: "3.6"

services:
  base-static: &base-static
    build:
      dockerfile: config/docker/Dockerfile.assets
      context: .
    networks:
      - main
    environment:
      - STATIC_PATH=/app/static
    volumes:
      - ./roulette:/app

  base-app: &base-app
    build:
      dockerfile: config/docker/Dockerfile.app
      context: .
    networks:
      - main
    volumes:
      - ./:/app

  webpack:
    <<: *base-static
    command: npm start

  admin:
    <<: *base-app
    command: [
        "python3.8",
        "-m",
        "SteamRoulette.admin",
        "--port",
        "5000",
        "--host",
        "0.0.0.0",
        "--config",
        "/app/config/app.yaml",
        "--debug",
        "true",
#        "--static_config",
#        "/app/SteamRoulette/static/manifest",
    ]
  nginx:
    image: nginx:1.14.0-alpine
    ports:
      - "5000:5000"
    volumes:
      - "./config/docker/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      main:
        aliases:
          - nginx
    depends_on:
      - admin
      - webpack

networks:
  main:
    driver: bridge
