FROM node:12.19.0-alpine3.11

RUN apk update && apk add libnotify && apk add gettext && rm -rf /var/cache/apk/*

WORKDIR /app

ENV NODE_PATH /app/node_modules/

ADD roulette/package.json .
ADD roulette/package-lock.json .

RUN npm install

ADD ./roulette/ .

ENV PATH /app/node_modules/.bin:$PATH
