FROM node:12.19.0-alpine3.11

RUN apk update && apk add libnotify && apk add gettext && rm -rf /var/cache/apk/*

WORKDIR /app

ENV STATIC_PATH /app/SteamRoulette/static
ENV NODE_PATH /app/node_modules/

ADD package.json .
ADD package-lock.json .

RUN npm install

ADD . .

ENV PATH /app/node_modules/.bin:$PATH
